#!/usr/bin/env bash
# Regenerates docker-compose.override.yml so `docker compose up` only mounts
# host accelerator devices (/dev/dri for GPU, /dev/accel for NPU) that
# actually exist on this host. Docker refuses to create a container at all if
# a declared `devices:` path doesn't exist on the host, instead of the app
# falling back to CPU the way it does for a missing model/service — this
# generates the device list dynamically instead of hardcoding it in
# docker-compose.yml, so a run on hardware without a GPU/NPU still starts.
#
# Usage: scripts/generate_device_overrides.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.."

OVERRIDE_FILE="docker-compose.override.yml"

{
  echo "# Auto-generated by scripts/generate_device_overrides.sh — do not edit by hand."
  echo "services:"
  echo "  local-lingua:"
  if [ -e /dev/dri ] || [ -e /dev/accel ]; then
    echo "    devices:"
    [ -e /dev/dri ] && echo "      - /dev/dri:/dev/dri"
    [ -e /dev/accel ] && echo "      - /dev/accel:/dev/accel"
  fi
  echo "  metrics-manager:"
  if [ -e /dev/dri ]; then
    echo "    devices:"
    echo "      - /dev/dri:/dev/dri"
  fi
} > "$OVERRIDE_FILE"

[ -e /dev/dri ] || echo "[devices] No /dev/dri — GPU device not mounted, CPU fallback only."
[ -e /dev/accel ] || echo "[devices] No /dev/accel — NPU device not mounted, app falls back automatically."
