// Copyright (C) 2025 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

import { FetchAPI } from '@/lib/api'
import { useMutation, useQuery } from '@tanstack/react-query'

const SYNTHETIC_IMAGE_API = new FetchAPI('/api/synthetic-image-generation')

export enum GenerationType {
  GOOD_DATASET = 'good_dataset',
  MISSING_COMPONENTS = 'missing_components',
  CUSTOM = 'custom',
}

function base64ToBlob(base64: string): Blob {
  const byteString = atob(base64)
  const arrayBuffer = new ArrayBuffer(byteString.length)
  const uint8Array = new Uint8Array(arrayBuffer)
  for (let i = 0; i < byteString.length; i++) {
    uint8Array[i] = byteString.charCodeAt(i)
  }
  return new Blob([uint8Array], { type: 'image/png' })
}

function validateProjectName(name: string): void {
  if (!name || !/^[a-zA-Z0-9_\-\s]+$/.test(name)) {
    throw new Error('Invalid project name: must be alphanumeric')
  }
}

export const useGetSyntheticImageHistory = (enabled: boolean = true) => {
  return useQuery({
    queryKey: ['synthetic-image-history'],
    queryFn: async () => {
      const data = await SYNTHETIC_IMAGE_API.get('image-gen/history')
      return data.images.map(
        (filename: string) =>
          `/api/synthetic-image-generation/outputs/${filename}`,
      ) as string[]
    },
    enabled,
  })
}

export const useGetSyntheticImageProjects = (enabled: boolean = true) => {
  return useQuery({
    queryKey: ['synthetic-image-projects'],
    queryFn: async () => {
      const data = await SYNTHETIC_IMAGE_API.get('projects')
      return (data.projects || []) as string[]
    },
    enabled,
  })
}

export const useGenerateSyntheticImage = () => {
  return useMutation({
    mutationFn: async ({
      baseImage64,
      type,
      objective,
      customPrompt,
      customType,
      projectName = 'default',
    }: {
      baseImage64: string
      type: GenerationType
      objective?: string
      customPrompt?: string
      customType?: string
      projectName?: string
    }) => {
      const blob = base64ToBlob(baseImage64)
      const formData = new FormData()
      formData.append('file', blob, 'image.png')

      let backendType = 'SYNTHETIC'
      if (type === GenerationType.MISSING_COMPONENTS)
        backendType = 'MISSING_COMPONENT'
      else if (type === GenerationType.CUSTOM) backendType = 'CUSTOM'

      formData.append('generation_type', backendType)
      if (objective) formData.append('objective', objective)
      if (customPrompt) formData.append('custom_prompt', customPrompt)
      if (customType) formData.append('custom_type', customType)
      formData.append('project_name', projectName)

      const data = await SYNTHETIC_IMAGE_API.post(
        'image-gen/generate',
        formData,
        { headers: {} },
      )

      if (!data.image) {
        throw new Error('No image returned from API')
      }

      const imageUrl = `/api/synthetic-image-generation/outputs/${data.image}`

      let finalPrompt = 'Variation generated by backend'
      if (type === GenerationType.MISSING_COMPONENTS) {
        finalPrompt = objective
          ? `Completing objective: ${objective}`
          : 'Completing objective'
      } else if (type === GenerationType.CUSTOM) {
        finalPrompt = customPrompt || 'Custom generation'
      }

      return { imageUrls: [imageUrl], finalPrompt }
    },
  })
}

export const useDeleteSyntheticImageAsset = () => {
  return useMutation({
    mutationFn: async (filename: string) => {
      await SYNTHETIC_IMAGE_API.delete(
        `image-gen/delete/${encodeURIComponent(filename)}`,
      )
    },
  })
}

export const useCreateSyntheticImageProject = () => {
  return useMutation({
    mutationFn: async (name: string) => {
      const formData = new FormData()
      formData.append('project_name', name)
      const data = await SYNTHETIC_IMAGE_API.post('projects/create', formData, {
        headers: {},
      })
      return data.project_name as string
    },
  })
}

export const useDeleteSyntheticImageProject = () => {
  return useMutation({
    mutationFn: async (name: string) => {
      validateProjectName(name)
      await SYNTHETIC_IMAGE_API.delete(
        `projects/delete/${encodeURIComponent(name)}`,
      )
    },
  })
}

export const useExportSyntheticImageProject = () => {
  return useMutation({
    mutationFn: async (name: string) => {
      validateProjectName(name)
      const response = (await SYNTHETIC_IMAGE_API.get(
        `projects/export/${encodeURIComponent(name)}`,
        { raw_response: true },
      )) as Response

      if (!response.ok) throw new Error('Failed to export project')

      const blob = await response.blob()
      const objectUrl = window.URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = objectUrl
      a.download = `${name}.zip`
      document.body.appendChild(a)
      a.click()
      window.URL.revokeObjectURL(objectUrl)
      document.body.removeChild(a)
    },
  })
}
