# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
services:   
  mongodb:
    image: mongo:latest
    hostname: mongodb
    networks:
      - app-network
    ports:
      - '27017:27017'
    volumes:
      - database:/data/db
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  app-network:
    
volumes:
  database: