#!/bin/bash
# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

APP_NAME="image-based-video-search"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUITE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SETUP_SCRIPT="$SUITE_ROOT/setup.sh"
SUITE_DIR="$SCRIPT_DIR/src"
MODELS_PATH="$SUITE_DIR/src/dlstreamer-pipeline-server/models"
SETUP_SENTINEL="$SUITE_DIR/.demo-studio-models-ready"
COMPOSE_FILE="$SUITE_DIR/compose.yml"
NGINX_CONF="$SUITE_DIR/src/nginx/nginx.conf"

# ── Parse optional port / device overrides ────────────────────────
IBVS_HTTP_PORT="${IBVS_HTTP_PORT:-80}"
IBVS_HTTPS_PORT="${IBVS_HTTPS_PORT:-443}"
IBVS_RTSP_PORT="${IBVS_RTSP_PORT:-8554}"
IBVS_DEVICE="${IBVS_DEVICE:-CPU}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --http-port)  IBVS_HTTP_PORT="$2";  shift 2 ;;
    --https-port) IBVS_HTTPS_PORT="$2"; shift 2 ;;
    --rtsp-port)  IBVS_RTSP_PORT="$2";  shift 2 ;;
    --device)     IBVS_DEVICE="$2";     shift 2 ;;
    *) shift ;;
  esac
done

OVERRIDE_FILE="$SCRIPT_DIR/compose.override.yml"

log() { echo "[$APP_NAME] $*"; }

generate_override() {
  local http_p="${http_proxy:-${HTTP_PROXY:-}}"
  local https_p="${https_proxy:-${HTTPS_PROXY:-}}"

  local has_proxy=false
  [[ -n "$http_p" || -n "$https_p" ]] && has_proxy=true

  local no_p=""
  if $has_proxy; then
    no_p="${no_proxy:-${NO_PROXY:-}}"
    # Add private IP ranges (for direct IP gRPC calls inside containers)
    for cidr in localhost 127.0.0.1 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16; do
      [[ "$no_p" == *"$cidr"* ]] || no_p="${no_p:+$no_p,}$cidr"
    done
    # Add 0.0.0.0 (milvus connects to its embedded etcd on 0.0.0.0:2379)
    # Use comma-delimited check to avoid false match against "10.0.0.0/8"
    [[ ",${no_p}," == *",0.0.0.0,"* ]] || no_p="${no_p:+$no_p,}0.0.0.0"
    # Add Docker service hostnames (service-name DNS bypasses the proxy)
    for svc in milvus-db milvus-ui feature-matching streaming-pipeline rtsp-server broker dlstreamer-pipeline-server app nginx; do
      [[ "$no_p" == *"$svc"* ]] || no_p="${no_p:+$no_p,}$svc"
    done
    # Add Docker container names — some services use container_name for DNS
    # (e.g. server.py calls ibvs-dlstreamer-pipeline-server directly)
    for cname in ibvs-milvusdb ibvs-milvusui ibvs-featurematching ibvs-streaming ibvs-mediamtx ibvs-broker ibvs-dlstreamer-pipeline-server ibvs-app ibvs-reverse-proxy; do
      [[ "$no_p" == *"$cname"* ]] || no_p="${no_p:+$no_p,}$cname"
    done
  fi

  # Map IBVS_DEVICE to the matching DLStreamer pipeline config file. Per the
  # upstream "How to use {GPU,NPU} for inference" docs, swapping which
  # config.{cpu,gpu,npu}.json is mounted at /home/pipeline-server/config.json
  # is what selects the inference device for both detection and classification.
  local device_lower selected_config
  device_lower="$(echo "${IBVS_DEVICE}" | tr '[:upper:]' '[:lower:]')"
  case "$device_lower" in
    gpu|gpu.*) selected_config="config.gpu.json" ;;
    npu)       selected_config="config.npu.json" ;;
    *)         selected_config="config.cpu.json" ;;
  esac
  log "Selecting DLStreamer pipeline config for device '${IBVS_DEVICE}' -> $selected_config"

  log "Generating compose override (proxy detected: $has_proxy)"

  if ! $has_proxy; then
    sed -i -E '/^[[:space:]]*-[[:space:]]+(http|https|HTTP|HTTPS|no|NO)_PROXY=[[:space:]]*$/d' "$COMPOSE_FILE"
  fi

  # Absolute path to the selected pipeline config. Using an absolute path keeps
  # the override valid regardless of where docker compose resolves relative
  # paths (the override file lives in $SCRIPT_DIR while the base compose lives
  # in $SUITE_DIR).
  local config_host_path="$SUITE_DIR/src/dlstreamer-pipeline-server/configs/filter-pipeline/$selected_config"
  local models_public_path="$SUITE_DIR/src/dlstreamer-pipeline-server/models/public"
  local models_resnet_path="$SUITE_DIR/src/dlstreamer-pipeline-server/models/resnet-50-pytorch"
  local broker_config_path="$SUITE_DIR/src/broker"

  emit_proxy_env() {
    local indent="$1"
    printf '%s- http_proxy=%s\n%s- https_proxy=%s\n%s- HTTP_PROXY=%s\n%s- HTTPS_PROXY=%s\n%s- no_proxy=%s\n%s- NO_PROXY=%s\n' \
      "$indent" "$http_p" "$indent" "$https_p" "$indent" "$http_p" "$indent" "$https_p" "$indent" "$no_p" "$indent" "$no_p"
  }

  {
    cat <<'HEADER'
# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Auto-generated by start.sh — do not edit manually.
# - Selects the DLStreamer pipeline device (CPU/GPU/NPU) by replacing the
#   dlstreamer-pipeline-server volume list (the device is encoded in
#   config.{cpu,gpu,npu}.json which gets mounted at /home/pipeline-server/config.json).
# - Overrides host ports for the nginx reverse proxy.
# - Propagates host proxy settings into containers when set.
services:
HEADER

    if $has_proxy; then
      for service in milvus-ui feature-matching streaming-pipeline rtsp-server app; do
        printf '  %s:\n    environment:\n' "$service"
        emit_proxy_env "      "
      done
    fi

    # dlstreamer-pipeline-server: always override volumes for device selection;
    # also reset the upstream `devices: ["/dev:/dev"]` which fails with
    # "create device inode /dev/pts/0: permission denied" because Docker
    # tries to register *every* node under /dev. Bind-mounting /dev as a
    # volume (below) already exposes the device nodes; only specific
    # accelerator nodes need an entry under `devices:` for cgroup access.
    printf '  dlstreamer-pipeline-server:\n'
    printf '    volumes: !override\n'
    printf '      - "%s:/home/pipeline-server/config.json"\n' "$config_host_path"
    printf '      - "dlstreamer-pipeline-server-pipeline-root:/var/cache/pipeline_root:uid=1999,gid=1999"\n'
    printf '      - "/run/udev:/run/udev:ro"\n'
    printf '      - "/dev:/dev"\n'
    printf '      - "dlstreamer-pipeline-server-tmp:/tmp"\n'
    printf '      - "%s:/models/public"\n' "$models_public_path"
    printf '      - "%s:/models/resnet-50-pytorch"\n' "$models_resnet_path"
    printf '    devices: !override\n'
    case "$device_lower" in
      gpu|gpu.*)
        # Intel GPU render node
        [ -e /dev/dri ] && printf '      - "/dev/dri:/dev/dri"\n'
        ;;
      npu)
        # Intel NPU accelerator node
        [ -e /dev/accel ] && printf '      - "/dev/accel:/dev/accel"\n'
        ;;
      *)
        # CPU: no accelerator device needed; emit empty list
        printf '      []\n'
        ;;
    esac
    # Also pass the selected device to the pipeline server via env so the
    # detection/classification gstreamer elements pick the right backend.
    local det_dev cls_dev
    case "$device_lower" in
      gpu|gpu.*) det_dev="GPU"; cls_dev="GPU" ;;
      npu)       det_dev="NPU"; cls_dev="NPU" ;;
      *)         det_dev="CPU"; cls_dev="CPU" ;;
    esac
    printf '    environment:\n'
    printf '      - DETECTION_DEVICE=%s\n' "$det_dev"
    printf '      - CLASSIFICATION_DEVICE=%s\n' "$cls_dev"
    if $has_proxy; then
      emit_proxy_env "      "
    fi

    printf '  milvus-db:\n    healthcheck:\n      start_period: 5m\n      retries: 10\n'
    if $has_proxy; then
      printf '    environment:\n'
      emit_proxy_env "      "
    fi

    printf '  broker:\n    volumes: !override\n      - "%s:/mosquitto/config:ro"\n' "$broker_config_path"
    if $has_proxy; then
      printf '    environment:\n'
      emit_proxy_env "      "
    fi

    printf '  nginx:\n    ports: !override\n      - "%s:80"\n      - "%s:443"\n      - "%s:8554"\n' \
      "$IBVS_HTTP_PORT" "$IBVS_HTTPS_PORT" "$IBVS_RTSP_PORT"

    if $has_proxy; then
      printf '    environment:\n'
      emit_proxy_env "      "
    fi

  } > "$OVERRIDE_FILE"
}

pull_image_with_retry() {
  local image="$1"
  local max_attempts="${2:-3}"
  local delay="${3:-5}"
  local attempt

  if docker image inspect "$image" >/dev/null 2>&1; then
    log "Docker image already available locally: $image"
    return 0
  fi

  for attempt in $(seq 1 "$max_attempts"); do
    log "Pulling docker image ($attempt/$max_attempts): $image"
    if docker pull "$image"; then
      log "Successfully pulled: $image"
      return 0
    fi

    if [ "$attempt" -lt "$max_attempts" ]; then
      log "Docker pull failed for $image. Retrying in ${delay}s..."
      sleep "$delay"
      delay=$((delay * 2))
    fi
  done

  log "ERROR: Failed to pull docker image after $max_attempts attempts: $image"
  log "Hint: check Docker Hub connectivity, proxy configuration, and try again."
  return 1
}

ensure_frontend_healthcheck() {
  if [ ! -f "$NGINX_CONF" ]; then
    log "ERROR: Nginx config not found at $NGINX_CONF"
    return 1
  fi

  if grep -q "Demo Studio redirects remaining HTTP requests to HTTPS" "$NGINX_CONF"; then
    return 0
  fi

  log "Configuring HTTP /nginx_healthz endpoint for Demo Studio health checks"
  local tmp_file
  tmp_file="$(mktemp)"

  if ! awk '
    /Demo Studio polls this endpoint over HTTP/ {
      skip_health = 1
      next
    }
    skip_health && /^[[:space:]]*location[[:space:]]*=[[:space:]]*\/nginx_healthz[[:space:]]*\{/ { next }
    skip_health && /^[[:space:]]*return[[:space:]]+200[[:space:]]+"ok\\n";/ { next }
    skip_health && /^[[:space:]]*add_header[[:space:]]+Content-Type[[:space:]]+text\/plain;/ { next }
    skip_health && /^[[:space:]]*\}/ {
      skip_health = 0
      next
    }
    !inserted && $0 ~ /^[[:space:]]*listen[[:space:]]+80;/ {
      print
      print ""
      print "        # Demo Studio polls this endpoint over HTTP before enabling the sample."
      print "        location = /nginx_healthz {"
      print "            return 200 \"ok\\n\";"
      print "            add_header Content-Type text/plain;"
      print "        }"
      print ""
      inserted = 1
      next
    }
    inserted && !redirected && $0 ~ /^[[:space:]]*return[[:space:]]+301[[:space:]]+https:\/\/\$host\$request_uri;/ {
      print "        # Demo Studio redirects remaining HTTP requests to HTTPS."
      print "        location / {"
      print "            return 301 https://$host$request_uri;"
      print "        }"
      redirected = 1
      next
    }
    { print }
    END { if (!inserted || !redirected) exit 42 }
  ' "$NGINX_CONF" > "$tmp_file"; then
    rm -f "$tmp_file"
    log "ERROR: Failed to update HTTP health endpoint in $NGINX_CONF"
    return 1
  fi

  mv "$tmp_file" "$NGINX_CONF"
}

# ── Step 1: Ensure the suite source is checked out ────────────────
log "Running suite setup ($SETUP_SCRIPT $APP_NAME)"
bash "$SETUP_SCRIPT" "$APP_NAME"

ensure_frontend_healthcheck

# ── Step 2: Download models (ResNet-50 + YOLOv11s) ────────────────
ensure_models() {
  if [ -f "$SETUP_SENTINEL" ]; then
    log "Models already downloaded (sentinel: $SETUP_SENTINEL)"
    return
  fi

  log "Downloading ResNet-50 + YOLOv11s models — this can take several minutes on first run"
  mkdir -p "$MODELS_PATH"

  # Pull images up front so transient registry/network failures are retried
  # with a clearer error message before model download starts.
  pull_image_with_retry "openvino/ubuntu24_dev:2024.6.0"
  pull_image_with_retry "intel/dlstreamer:2026.0.0-ubuntu24"

  # ResNet-50
  docker run --rm --user=root \
    -e http_proxy="${http_proxy:-}" -e https_proxy="${https_proxy:-}" -e no_proxy="${no_proxy:-}" \
    -e HTTP_PROXY="${HTTP_PROXY:-}" -e HTTPS_PROXY="${HTTPS_PROXY:-}" \
    -v "$MODELS_PATH:/output" \
    openvino/ubuntu24_dev:2024.6.0 bash -c "\
      omz_downloader --name resnet-50-pytorch --output_dir models && \
      omz_converter --name resnet-50-pytorch --download_dir models --output_dir models && \
      cp -r ./models/public/resnet-50-pytorch /output && \
      chown -R $(id -u):$(id -g) /output"

  # YOLOv11s
  docker run --rm --user=root \
    -e http_proxy="${http_proxy:-}" -e https_proxy="${https_proxy:-}" -e no_proxy="${no_proxy:-}" \
    -e HTTP_PROXY="${HTTP_PROXY:-}" -e HTTPS_PROXY="${HTTPS_PROXY:-}" \
    -e HOST_UID="$(id -u)" -e HOST_GID="$(id -g)" \
    -v "$MODELS_PATH:/output" \
    intel/dlstreamer:2026.0.0-ubuntu24 bash -c '
      mkdir -p /output/public
      export MODELS_PATH=/output
      chmod +x /home/dlstreamer/dlstreamer/samples/download_public_models.sh
      if [ ! -e "/output/public/yolo11s/FP16/yolo11s.xml" ]; then
        for attempt in 1 2 3; do
          echo "Attempt $attempt: Running model download and quantization..."
          if /home/dlstreamer/dlstreamer/samples/download_public_models.sh yolo11s coco128; then
            echo "Model download and quantization successful!"
            break
          fi
          echo "Download attempt $attempt failed. Retrying..."
          sleep 2
        done
      fi
      chown -R "$HOST_UID:$HOST_GID" /output
    '

  touch "$SETUP_SENTINEL"
  log "Model setup complete"
}

ensure_models

# ── Generate compose override (proxy-aware + device-aware) ───────
# Device selection (CPU/GPU/NPU) is applied via the override file by
# replacing the dlstreamer-pipeline-server volume list — the upstream
# src/compose.yml is left untouched on purpose.
generate_override

# ── Step 3: Bring up the docker compose stack ────────────────────
COMPOSE_ARGS=(-f "$COMPOSE_FILE")
[ -f "$OVERRIDE_FILE" ] && COMPOSE_ARGS+=(-f "$OVERRIDE_FILE")

existing_containers="$(cd "$SUITE_DIR" && docker compose "${COMPOSE_ARGS[@]}" ps -q 2>/dev/null)" || existing_containers=""
if [ -n "$existing_containers" ]; then
  log "Stack is already running — bringing it down before restart"
  (cd "$SUITE_DIR" && docker compose "${COMPOSE_ARGS[@]}" down)
fi

wait_for_healthy() {
  local timeout_seconds=600
  local poll_interval_seconds=5
  local elapsed_seconds=0

  log "Waiting for all containers to become healthy (timeout: ${timeout_seconds}s)..."

  while [ "$elapsed_seconds" -lt "$timeout_seconds" ]; do
    local starting=0
    local containers
    containers=$(cd "$SUITE_DIR" && docker compose "${COMPOSE_ARGS[@]}" ps -q 2>/dev/null)

    if [ -z "$containers" ]; then
      log "ERROR: No containers found after start"
      return 1
    fi

    while IFS= read -r cid; do
      local name state health
      name=$(docker inspect --format '{{.Name}}' "$cid" 2>/dev/null | sed 's|^/||')
      state=$(docker inspect --format '{{.State.Status}}' "$cid" 2>/dev/null)
      health=$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "$cid" 2>/dev/null)

      if [ "$state" = "exited" ] || [ "$state" = "dead" ]; then
        log "ERROR: Container $name stopped unexpectedly (state: $state)"
        return 1
      fi
      if [ "$health" = "unhealthy" ]; then
        log "ERROR: Container $name is unhealthy"
        return 1
      fi
      # Has a healthcheck and it hasn't passed yet
      if [ "$health" = "starting" ]; then
        starting=$((starting + 1))
      # No healthcheck — require at least state=running (guards against created/restarting)
      elif [ "$health" = "none" ] && [ "$state" != "running" ]; then
        starting=$((starting + 1))
      fi
    done <<< "$containers"

    if [ "$starting" -eq 0 ]; then
      log "All containers are healthy"
      return 0
    fi

    sleep "$poll_interval_seconds"
    elapsed_seconds=$((${elapsed_seconds:-0} + ${poll_interval_seconds:-5}))
    log "Waiting for $starting container(s) to become healthy... (${elapsed_seconds}/${timeout_seconds}s)"
  done

  log "ERROR: Timed out after ${timeout_seconds}s — some containers are still not healthy"
  return 1
}

cleanup() {
  log "Received shutdown signal — running 'docker compose down'"
  (cd "$SUITE_DIR" && docker compose "${COMPOSE_ARGS[@]}" down) || true
}
trap cleanup EXIT INT TERM

log "Starting docker compose stack (detached)"
cd "$SUITE_DIR"
docker compose "${COMPOSE_ARGS[@]}" up -d
wait_for_healthy
log "Stack is up and healthy — access the UI at https://localhost:${IBVS_HTTPS_PORT}/"

# Keep this process alive so the frontend sees an active PID.
# docker compose logs -f also forwards all container output to the
# frontend's log viewer and exits naturally if the stack goes down.
docker compose "${COMPOSE_ARGS[@]}" logs -f
