camera:
  fps: 30
  height: 480
  type: realsense
  width: 848
client:
  api_key: '-'
  base_url: http://127.0.0.1:8080/api/text-generation/v1
  model_id: openvino:OpenVINO/Qwen3.5-4B-int4-ov
fastsam:
  device: NPU
  image_size: 1024
  img_path: ./data/coco_bike.jpg
  name: FastSAM-x
inference:
  bbox:
  - 189
  - 78
  - 643
  - 414
robot:
  gripper_close: 40.0
  gripper_open: 60.0
  offset_x: 130
  offset_y: -10
  offset_z: 5
  port: /dev/ttyACM0
  type: SO-ARM101
