[project]
name = "robotics-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "clip",
    "cmeel-urdfdom>=4,<5",
    "fastapi[all]>=0.137.0",
    "fastmcp>=3.4.2",
    "feetech-servo-sdk>=1.0.0",
    "lerobot[kinematics]>=0.5.1",
    "openai>=2.41.1",
    "openvino>=2026.2.0",
    "placo<0.9.16",
    "pyrealsense2>=2.58.2.10647",
    "sse-starlette>=3.4.4",
    "supervision>=0.28.0",
    "ultralytics>=8.4.67",
]

[tool.uv.sources]
clip = { git = "https://github.com/openai/CLIP.git" }

[tool.uv]
index-strategy = "unsafe-best-match"

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/xpu"
