// Copyright (C) 2025 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

import { EndpointProps } from '../endpoint'

export const imageGenerationEndpoints: EndpointProps[] = [
  {
    title: 'Image Generation API',
    description:
      'Generate images from text prompts using diffusion models via OpenAI-compatible API.',
    path: '/v3/images/generations',
    method: 'POST',
    headers: 'Content-Type: application/json',
    body: `{
    "model": "OpenVINO/stable-diffusion-v1-5-int8-ov",
    "prompt": "Three astronauts on the moon, cold color palette, muted colors, detailed, 8k",
    "rng_seed": 409,
    "num_inference_steps": 50,
    "size": "512x512"
}`,
    output: `>(jq -r '.data[0].b64_json' | base64 --decode > generate_output.png) `,
    exampleResponse: `{
  "data": [
    {
      "b64_json": "..."
    }
  ]
}`,
    parameters: [
      {
        name: 'model',
        description:
          'Name of the model to use. From administrator point of view it is the name assigned to a MediaPipe graph configured to schedule generation using desired model.',
        required: true,
      },
      {
        name: 'prompt',
        description: 'A text description of the desired image(s).',
        required: true,
      },
      {
        name: 'size',
        description:
          'The size of the generated images. Must be in WxH format, example: 1024x768. Default model W/H will be used when using auto.',
        required: false,
      },
      {
        name: 'n',
        description:
          'A number of images to generate. If you want to generate multiple images for the same combination of generation parameters and text prompts, you can use this parameter for better performance as internally computations will be performed with batch for Unet / Transformer models and text embeddings tensors will also be computed only once. Default: 1',
        required: false,
      },
      {
        name: 'prompt_2',
        description:
          'Prompt 2 for models which have at least two text encoders (SDXL/SD3/FLUX).',
        required: false,
      },
      {
        name: 'prompt_3',
        description:
          'Prompt 3 for models which have at least three text encoders (SD3).',
        required: false,
      },
      {
        name: 'negative_prompt',
        description:
          'Negative prompt for models which support negative prompt (SD/SDXL/SD3).',
        required: false,
      },
      {
        name: 'negative_prompt_2',
        description:
          'Negative prompt 2 for models which support negative prompt (SDXL/SD3).',
        required: false,
      },
      {
        name: 'negative_prompt_3',
        description:
          'Negative prompt 3 for models which support negative prompt (SD/SDXL/SD3).',
        required: false,
      },
      {
        name: 'num_inference_steps',
        description:
          'Defines denoising iteration count. Higher values increase quality and generation time, lower values generate faster with less detail. Default: 50',
        required: false,
      },
      {
        name: 'guidance_scale',
        description:
          'Guidance scale parameter which controls how model sticks to text embeddings generated by text encoders within a pipeline. Higher value of guidance scale moves image generation towards text embeddings, but resulting image will be less natural and more augmented.',
        required: false,
      },
      {
        name: 'rng_seed',
        description: 'Seed for random generator.',
        required: false,
      },
      {
        name: 'max_sequence_length',
        description: `This parameters limits max sequence length for T5 encoder for SD3 and FLUX models. T5 tokenizer output is padded with pad tokens to 'max_sequence_length' within a pipeline. So, for better performance, you can specify this parameter to lower value to speed-up T5 encoder inference as well as inference of transformer denoising model. For optimal performance it can be set to a number of tokens for prompt_3 / negative_prompt_3 for SD3 or prompt_2 for FLUX.`,
        required: false,
      },
    ],
  },
  {
    title: 'Image Edit API',
    description:
      'Create edited or extended images given an original image and a prompt.',
    path: '/v3/images/edits',
    method: 'POST',
    headers: 'Content-Type: multipart/form-data',
    formData: [
      'model=OpenVINO/stable-diffusion-v1-5-int8-ov',
      'image=@generate_output.png',
      'prompt=Three astronauts in the jungle, vibrant color palette, live colors, detailed, 8k',
      'rng_seed=409',
      'size=512x512',
      'num_inference_steps=50',
      'strength=0.67',
    ],
    output: `>(jq -r '.data[0].b64_json' | base64 --decode > edit_output.png) `,
    exampleResponse: `{
  "data": [
    {
      "b64_json": "..."
    }
  ]
}`,
    parameters: [
      {
        name: 'model',
        description:
          'Name of the model to use. From administrator point of view it is the name assigned to a MediaPipe graph configured to schedule generation using desired model.',
        required: true,
      },
      {
        name: 'image',
        description:
          'The image to edit. Must be a single image (Note: Array of strings is not supported for now.)',
        required: true,
      },
      {
        name: 'prompt',
        description: 'A text description of the desired image(s).',
        required: true,
      },
      {
        name: 'size',
        description:
          'The size of the generated images. Must be in WxH format, example: 1024x768. Default model W/H will be used when using auto.',
        required: false,
      },
      {
        name: 'n',
        description:
          'A number of images to generate. If you want to generate multiple images for the same combination of generation parameters and text prompts, you can use this parameter for better performance as internally computations will be performed with batch for Unet / Transformer models and text embeddings tensors will also be computed only once. Default: 1',
        required: false,
      },
      {
        name: 'prompt_2',
        description:
          'Prompt 2 for models which have at least three text encoders (SD3).',
        required: false,
      },
      {
        name: 'prompt_3',
        description:
          'Prompt 3 for models which have at least three text encoders (SD3).',
        required: false,
      },
      {
        name: 'negative_prompt',
        description:
          'Negative prompt for models which support negative prompt (SD/SDXL/SD3).',
        required: false,
      },
      {
        name: 'negative_prompt_2',
        description:
          'Negative prompt 2 for models which support negative prompt (SDXL/SD3).',
        required: false,
      },
      {
        name: 'negative_prompt_3',
        description:
          'Negative prompt 3 for models which support negative prompt (SD/SDXL/SD3).',
        required: false,
      },
      {
        name: 'num_inference_steps',
        description:
          'Defines denoising iteration count. Higher values increase quality and generation time, lower values generate faster with less detail. Default: 50',
        required: false,
      },
      {
        name: 'guidance_scale',
        description:
          'Guidance scale parameter which controls how model sticks to text embeddings generated by text encoders within a pipeline. Higher value of guidance scale moves image generation towards text embeddings, but resulting image will be less natural and more augmented.',
        required: false,
      },
      {
        name: 'strength',
        description:
          'Indicates extent to transform the reference image. Must be between 0 and 1. Image is used as a starting point and more noise is added the higher the strength. The number of denoising steps depends on the amount of noise initially added. When strength is 1, added noise is maximum and the denoising process runs for the full number of iterations specified in num_inference_steps. A value of 1 essentially ignores image parameter. Min: 0.0, Max: 1.0',
        required: false,
      },
      {
        name: 'rng_seed',
        description: 'Seed for random generator.',
        required: false,
      },
      {
        name: 'max_sequence_length',
        description: `This parameters limits max sequence length for T5 encoder for SD3 and FLUX models. T5 tokenizer output is padded with pad tokens to 'max_sequence_length' within a pipeline. So, for better performance, you can specify this parameter to lower value to speed-up T5 encoder inference as well as inference of transformer denoising model. For optimal performance it can be set to a number of tokens for prompt_3 / negative_prompt_3 for SD3 or prompt_2 for FLUX.`,
        required: false,
      },
    ],
  },
]
