# Copyright 2025 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.

Example:

```shell
lerobot-record \
    --robot.type=so100_follower \
    --robot.port=/dev/tty.usbmodem58760431541 \
    --robot.cameras="{laptop: {type: opencv, index_or_path: 0, width: 640, height: 480, fps: 30}}" \
    --robot.id=black \
    --dataset.repo_id=<my_username>/<my_dataset_name> \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube" \
    --display_data=true
    # <- Teleop optional if you want to teleoperate to record or in between episodes with a policy \
    # --teleop.type=so100_leader \
    # --teleop.port=/dev/tty.usbmodem58760431551 \
    # --teleop.id=blue \
    # <- Policy optional if you want to record with a policy \
    # --policy.path=${HF_USER}/my_policy \
```

Example recording with bimanual so100:
```shell
lerobot-record \
  --robot.type=bi_so100_follower \
  --robot.left_arm_port=/dev/tty.usbmodem5A460851411 \
  --robot.right_arm_port=/dev/tty.usbmodem5A460812391 \
  --robot.id=bimanual_follower \
  --robot.cameras='{
    left: {"type": "opencv", "index_or_path": 0, "width": 640, "height": 480, "fps": 30},
    top: {"type": "opencv", "index_or_path": 1, "width": 640, "height": 480, "fps": 30},
    right: {"type": "opencv", "index_or_path": 2, "width": 640, "height": 480, "fps": 30}
  }' \
  --teleop.type=bi_so100_leader \
  --teleop.left_arm_port=/dev/tty.usbmodem5A460828611 \
  --teleop.right_arm_port=/dev/tty.usbmodem5A460826981 \
  --teleop.id=bimanual_leader \
  --display_data=true \
  --dataset.repo_id=${HF_USER}/bimanual-so100-handover-cube \
  --dataset.num_episodes=25 \
  --dataset.single_task="Grab and handover the red cube to the other arm"
```
"""

import logging
import re
import time
from collections import deque
from copy import copy
from dataclasses import asdict, dataclass, field
from pathlib import Path
from pprint import pformat
from typing import Any, Iterable, Mapping

import numpy as np
import openvino as ov
import openvino.properties as props
import torch

from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_realsense import (
    RealSenseCameraConfig,
)  # noqa: F401
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig
from lerobot.configs.types import FeatureType
from lerobot.datasets.image_writer import safe_stop_image_writer
from lerobot.datasets.lerobot_dataset import LeRobotDataset, LeRobotDatasetMetadata
from lerobot.datasets.pipeline_features import (
    aggregate_pipeline_dataset_features,
    create_initial_features,
)
from lerobot.datasets.utils import (
    build_dataset_frame,
    combine_feature_dicts,
    dataset_to_policy_features,
)
from lerobot.datasets.video_utils import VideoEncodingManager
from lerobot.policies.factory import make_policy, make_pre_post_processors
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.policies.utils import make_robot_action, prepare_observation_for_inference
from lerobot.processor import (
    PolicyAction,
    PolicyProcessorPipeline,
    RobotAction,
    RobotObservation,
    RobotProcessorPipeline,
    make_default_processors,
)
from lerobot.processor.rename_processor import rename_stats
from lerobot.robots import (  # noqa: F401
    Robot,
    RobotConfig,
    bi_so100_follower,
    hope_jr,
    koch_follower,
    make_robot_from_config,
    so100_follower,
    so101_follower,
)
from lerobot.teleoperators import (  # noqa: F401
    Teleoperator,
    TeleoperatorConfig,
    bi_so100_leader,
    homunculus,
    koch_leader,
    make_teleoperator_from_config,
    so100_leader,
    so101_leader,
)
from lerobot.teleoperators.keyboard.teleop_keyboard import KeyboardTeleop
from lerobot.utils.constants import ACTION, OBS_STR
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    predict_action,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.utils.import_utils import register_third_party_devices
from lerobot.utils.robot_utils import busy_wait
from lerobot.utils.utils import (
    get_safe_torch_device,
    init_logging,
    log_say,
)
from lerobot.utils.visualization_utils import init_rerun, log_rerun_data


class OpenVINOInference:
    """Thin wrapper around an OpenVINO compiled model with action chunk management."""

    def __init__(
        self,
        model_path: str | Path,
        device: str,
        enable_npu_high_precision: bool,
        action_chunk_size: int,
        input_features: Mapping[str, Any] | None = None,
        rename_map: Mapping[str, str] | None = None,
    ) -> None:
        resolved_path = self._resolve_model_path(model_path)
        if not resolved_path.exists():
            raise FileNotFoundError(
                f"OpenVINO model path does not exist: {resolved_path}"
            )

        core = ov.Core()
        ov_model = core.read_model(resolved_path.as_posix())

        compile_properties = {
            props.hint.performance_mode(): props.hint.PerformanceMode.LATENCY,
        }
        if device.upper() == "NPU" and enable_npu_high_precision:
            compile_properties["NPU_COMPILATION_MODE_PARAMS"] = (
                "compute-layers-with-higher-precision=Sqrt,Power,ReduceMean,Add"
            )

        self.compiled_model = core.compile_model(ov_model, device, compile_properties)
        self.input_names = [
            input_tensor.any_name for input_tensor in self.compiled_model.inputs
        ]
        self.action_queue: deque[np.ndarray] = deque([], maxlen=action_chunk_size)
        self.input_features = (
            dict(input_features) if input_features is not None else None
        )
        self.rename_map = dict(rename_map) if rename_map is not None else {}
        self._inverse_rename_map = {v: k for k, v in self.rename_map.items()}
        self._alias_lookup = self._build_alias_lookup()
        self._ov_input_to_actual_key = self._map_inputs_to_features(
            self.compiled_model.inputs
        )

    @staticmethod
    def _resolve_model_path(path_like: str | Path) -> Path:
        candidate = Path(path_like)
        if candidate.is_dir():
            xml_files = sorted(candidate.glob("*.xml"))
            if not xml_files:
                raise FileNotFoundError(
                    f"No .xml model found in directory: {candidate}"
                )
            return xml_files[0]
        return candidate

    def reset(self) -> None:
        self.action_queue.clear()

    def infer(self, processed_obs: dict[str, torch.Tensor]) -> torch.Tensor:
        if not self.action_queue:
            model_inputs: dict = {}
            if self.input_features is None:
                processed_values = list(processed_obs.values())
                if len(processed_values) != len(self.compiled_model.inputs):
                    processed_lookup = self._build_processed_obs_lookup(processed_obs)
                    for input_tensor in self.compiled_model.inputs:
                        ov_name = input_tensor.any_name
                        selected_key = self._resolve_processed_key_for_input(
                            ov_name,
                            processed_obs,
                            processed_lookup,
                        )
                        if selected_key is None:
                            available = ", ".join(sorted(processed_obs.keys()))
                            raise ValueError(
                                "Unable to match OpenVINO input '"
                                f"{ov_name}' with processed observation keys. Available keys: {available}."
                            )
                        model_inputs[input_tensor] = self._to_numpy(
                            processed_obs[selected_key]
                        )
                else:
                    for input_tensor, tensor in zip(
                        self.compiled_model.inputs, processed_values
                    ):
                        model_inputs[input_tensor] = self._to_numpy(tensor)
            else:
                processed_lookup = self._build_processed_obs_lookup(processed_obs)
                for input_tensor in self.compiled_model.inputs:
                    ov_name = input_tensor.any_name
                    selected_key = self._resolve_processed_key_for_input(
                        ov_name,
                        processed_obs,
                        processed_lookup,
                    )
                    if selected_key is None:
                        available = ", ".join(sorted(processed_obs.keys()))
                        raise ValueError(
                            "Unable to match OpenVINO input '"
                            f"{ov_name}' with processed observation keys. Available keys: {available}."
                        )
                    model_inputs[input_tensor] = self._to_numpy(
                        processed_obs[selected_key]
                    )

            results = self.compiled_model(model_inputs)
            action_chunk = results[0]

            if hasattr(action_chunk, "numpy"):
                action_chunk_np = action_chunk.numpy()
            else:
                action_chunk_np = np.asarray(action_chunk)
            if action_chunk_np.ndim < 3:
                raise ValueError(
                    "OpenVINO model output must be shaped as (batch, chunk, action_dim)."
                )
            for action in action_chunk_np[0]:
                self.action_queue.append(action.astype(np.float32, copy=False))

        action_np = self.action_queue.popleft()
        action_tensor = torch.from_numpy(action_np).unsqueeze(0)
        return action_tensor

    def _build_alias_lookup(self) -> dict[str, str]:
        alias_lookup: dict[str, str] = {}
        if self.input_features is None:
            return alias_lookup
        for feature_key in self.input_features.keys():
            actual_key = self.rename_map.get(feature_key, feature_key)
            for alias in (
                feature_key,
                actual_key,
                self._sanitize_key(feature_key),
                self._sanitize_key(actual_key),
            ):
                alias_lookup[alias] = actual_key
        return alias_lookup

    def _map_inputs_to_features(
        self, compiled_inputs: Iterable[Any]
    ) -> dict[str, str | None]:
        mapping: dict[str, str | None] = {}
        if not self._alias_lookup:
            return mapping
        for input_tensor in compiled_inputs:
            ov_name = input_tensor.any_name
            actual = self._alias_lookup.get(ov_name)
            if actual is None:
                actual = self._alias_lookup.get(self._sanitize_key(ov_name))
            mapping[ov_name] = actual
        return mapping

    def _candidate_keys_for_input(self, ov_name: str) -> list[str]:
        candidates: list[str] = []
        mapped_actual = self._ov_input_to_actual_key.get(ov_name)
        if mapped_actual:
            candidates.append(mapped_actual)
            sanitized_actual = self._sanitize_key(mapped_actual)
            if sanitized_actual != mapped_actual:
                candidates.append(sanitized_actual)
            original_key = self._inverse_rename_map.get(mapped_actual)
            if original_key:
                candidates.append(original_key)
                sanitized_original = self._sanitize_key(original_key)
                if sanitized_original != original_key:
                    candidates.append(sanitized_original)
        alias_actual = self._alias_lookup.get(ov_name)
        if alias_actual:
            candidates.append(alias_actual)
        sanitized_name = self._sanitize_key(ov_name)
        alias_actual = self._alias_lookup.get(sanitized_name)
        if alias_actual:
            candidates.append(alias_actual)
        candidates.append(ov_name)
        if sanitized_name != ov_name:
            candidates.append(sanitized_name)
        inverse_alias = self._inverse_rename_map.get(ov_name)
        if inverse_alias:
            actual_from_inverse = self.rename_map.get(inverse_alias, inverse_alias)
            candidates.append(actual_from_inverse)
            sanitized_inverse = self._sanitize_key(inverse_alias)
            if sanitized_inverse != inverse_alias:
                candidates.append(sanitized_inverse)
        return self._dedupe_candidates(candidates)

    @staticmethod
    def _sanitize_key(name: str) -> str:
        sanitized = re.sub(r"[^0-9A-Za-z_]", "_", name)
        return sanitized or "_"

    @staticmethod
    def _dedupe_candidates(candidates: list[str]) -> list[str]:
        seen: set[str] = set()
        ordered: list[str] = []
        for candidate in candidates:
            if candidate is None or candidate in seen:
                continue
            seen.add(candidate)
            ordered.append(candidate)
        return ordered

    def _build_processed_obs_lookup(
        self, processed_obs: Mapping[str, Any]
    ) -> dict[str, str]:
        lookup: dict[str, str] = {}
        for key in processed_obs.keys():
            for variant in self._expand_key_variants(key):
                lookup.setdefault(variant, key)
            original_key = self._inverse_rename_map.get(key)
            if original_key:
                for variant in self._expand_key_variants(original_key):
                    lookup.setdefault(variant, key)
        for source, target in self.rename_map.items():
            if source in processed_obs:
                for variant in self._expand_key_variants(target):
                    lookup.setdefault(variant, source)
            if target in processed_obs:
                for variant in self._expand_key_variants(source):
                    lookup.setdefault(variant, target)
        return lookup

    def _resolve_processed_key_for_input(
        self,
        ov_name: str,
        processed_obs: Mapping[str, Any],
        lookup: Mapping[str, str],
    ) -> str | None:
        for candidate in self._candidate_keys_for_input(ov_name):
            if candidate in processed_obs:
                return candidate
            matched = lookup.get(candidate)
            if matched and matched in processed_obs:
                return matched
        return None

    def _expand_key_variants(self, key: str) -> list[str]:
        variants = [key]
        sanitized = self._sanitize_key(key)
        if sanitized != key:
            variants.append(sanitized)
        split_segments = re.split(r"[./:]", key)
        if len(split_segments) > 1:
            variants.append("_".join(segment for segment in split_segments if segment))
            variants.append(split_segments[-1])
        return self._dedupe_candidates([variant for variant in variants if variant])

    @staticmethod
    def _to_numpy(value: Any) -> np.ndarray:
        if isinstance(value, torch.Tensor):
            return value.detach().cpu().numpy()
        if isinstance(value, np.ndarray):
            return value
        raise TypeError(
            "Processed observation values must be torch.Tensor or numpy.ndarray. "
            f"Received type: {type(value).__name__}."
        )


def predict_action_openvino(
    observation: dict[str, np.ndarray],
    ov_session: OpenVINOInference,
    preprocessor: PolicyProcessorPipeline[dict[str, Any], dict[str, Any]],
    postprocessor: PolicyProcessorPipeline[PolicyAction, PolicyAction],
    task: str | None = None,
    robot_type: str | None = None,
) -> PolicyAction:
    observation_copy = copy(observation)
    torch_device = torch.device("cpu")
    observation_tensor = prepare_observation_for_inference(
        observation_copy,
        device=torch_device,
        task=task,
        robot_type=robot_type,
    )
    processed_observation = preprocessor(observation_tensor)
    action_tensor = ov_session.infer(processed_observation)
    action = postprocessor(action_tensor)
    return action


@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path').
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 60
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 60
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4
    # Number of episodes to record before batch encoding videos
    # Set to 1 for immediate encoding (default behavior), or higher for batched encoding
    video_encoding_batch_size: int = 1
    # Rename map for the observation to override the image and state keys
    rename_map: dict[str, str] = field(default_factory=dict)

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | None = None
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # Resume recording on an existing dataset.
    resume: bool = False
    # Optional OpenVINO IR path (XML file or directory containing it) for accelerated policy inference.
    openvino_model_path: str | Path | None = None
    # Target device plugin for OpenVINO (e.g., "CPU", "GPU", "NPU").
    openvino_device: str = "CPU"
    # Enable enhanced precision for Intel NPU targets.
    openvino_enable_npu_high_precision: bool = False

    def __post_init__(self):
        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")
        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")
            self.policy = PreTrainedConfig.from_pretrained(
                policy_path, cli_overrides=cli_overrides
            )
            self.policy.pretrained_path = policy_path

        if self.teleop is None and self.policy is None:
            raise ValueError(
                "Choose a policy, a teleoperator or both to control the robot"
            )

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]


""" --------------- record_loop() data flow --------------------------
       [ Robot ]
           V
     [ robot.get_observation() ] ---> raw_obs
           V
     [ robot_observation_processor ] ---> processed_obs
           V
     .-----( ACTION LOGIC )------------------.
     V                                       V
     [ From Teleoperator ]                   [ From Policy ]
     |                                       |
     |  [teleop.get_action] -> raw_action    |   [predict_action]
     |          |                            |          |
     |          V                            |          V
     | [teleop_action_processor]             |          |
     |          |                            |          |
     '---> processed_teleop_action           '---> processed_policy_action
     |                                       |
     '-------------------------.-------------'
                               V
                  [ robot_action_processor ] --> robot_action_to_send
                               V
                    [ robot.send_action() ] -- (Robot Executes)
                               V
                    ( Save to Dataset )
                               V
                  ( Rerun Log / Loop Wait )
"""


@safe_stop_image_writer
def record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    teleop_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs after teleop
    robot_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs before robot
    robot_observation_processor: RobotProcessorPipeline[
        RobotObservation, RobotObservation
    ],  # runs after robot
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    policy: PreTrainedPolicy | None = None,
    ov_session: OpenVINOInference | None = None,
    preprocessor: PolicyProcessorPipeline[dict[str, Any], dict[str, Any]] | None = None,
    postprocessor: PolicyProcessorPipeline[PolicyAction, PolicyAction] | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(
            f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps})."
        )

    teleop_arm = teleop_keyboard = None
    if isinstance(teleop, list):
        teleop_keyboard = next(
            (t for t in teleop if isinstance(t, KeyboardTeleop)), None
        )
        teleop_arm = next(
            (
                t
                for t in teleop
                if isinstance(
                    t,
                    (
                        so100_leader.SO100Leader
                        | so101_leader.SO101Leader
                        | koch_leader.KochLeader
                    ),
                )
            ),
            None,
        )

        if not (
            teleop_arm
            and teleop_keyboard
            and len(teleop) == 2
            and robot.name == "lekiwi_client"
        ):
            raise ValueError(
                "For multi-teleop, the list must contain exactly one KeyboardTeleop and one arm teleoperator. Currently only supported for LeKiwi robot."
            )

    # Reset policy and processor if they are provided
    if policy is not None and preprocessor is not None and postprocessor is not None:
        policy.reset()
        preprocessor.reset()
        postprocessor.reset()
    if ov_session is not None:
        ov_session.reset()

    timestamp = 0
    start_episode_t = time.perf_counter()
    while timestamp < control_time_s:
        start_loop_t = time.perf_counter()

        if events["exit_early"]:
            events["exit_early"] = False
            break

        # Get robot observation
        obs = robot.get_observation()

        # Applies a pipeline to the raw robot observation, default is IdentityProcessor
        obs_processed = robot_observation_processor(obs)

        if policy is not None or ov_session is not None or dataset is not None:
            if dataset is None:
                raise ValueError(
                    "Dataset must be provided when running policy or OpenVINO inference."
                )
            observation_frame = build_dataset_frame(
                dataset.features, obs_processed, prefix=OBS_STR
            )

        # Get action from either policy or teleop
        act_processed_policy: RobotAction | None = None
        act_processed_teleop: RobotAction | None = None

        if (
            ov_session is not None
            and preprocessor is not None
            and postprocessor is not None
            and dataset is not None
        ):
            policy_action = predict_action_openvino(
                observation=observation_frame,
                ov_session=ov_session,
                preprocessor=preprocessor,
                postprocessor=postprocessor,
                task=single_task,
                robot_type=robot.robot_type,
            )
            act_processed_policy = make_robot_action(policy_action, dataset.features)

        elif (
            policy is not None
            and preprocessor is not None
            and postprocessor is not None
            and dataset is not None
        ):
            policy_action = predict_action(
                observation=observation_frame,
                policy=policy,
                device=get_safe_torch_device(policy.config.device),
                preprocessor=preprocessor,
                postprocessor=postprocessor,
                use_amp=policy.config.use_amp,
                task=single_task,
                robot_type=robot.robot_type,
            )

            act_processed_policy = make_robot_action(policy_action, dataset.features)

        elif policy is None and isinstance(teleop, Teleoperator):
            act = teleop.get_action()

            # Applies a pipeline to the raw teleop action, default is IdentityProcessor
            act_processed_teleop = teleop_action_processor((act, obs))

        elif policy is None and isinstance(teleop, list):
            arm_action = teleop_arm.get_action()
            arm_action = {f"arm_{k}": v for k, v in arm_action.items()}
            keyboard_action = teleop_keyboard.get_action()
            base_action = robot._from_keyboard_to_base_action(keyboard_action)
            act = {**arm_action, **base_action} if len(base_action) > 0 else arm_action
            act_processed_teleop = teleop_action_processor((act, obs))
        else:
            logging.info(
                "No policy or teleoperator provided, skipping action generation."
                "This is likely to happen when resetting the environment without a teleop device."
                "The robot won't be at its rest position at the start of the next episode."
            )
            continue

        # Applies a pipeline to the action, default is IdentityProcessor
        if act_processed_policy is not None:
            action_values = act_processed_policy
            robot_action_to_send = robot_action_processor((act_processed_policy, obs))
        elif act_processed_teleop is not None:
            action_values = act_processed_teleop
            robot_action_to_send = robot_action_processor((act_processed_teleop, obs))
        else:
            logging.info(
                "No valid action produced after processing. Skipping this control step to avoid sending invalid commands."
            )
            continue

        # Send action to robot
        # Action can eventually be clipped using `max_relative_target`,
        # so action actually sent is saved in the dataset. action = postprocessor.process(action)
        # TODO(steven, pepijn, adil): we should use a pipeline step to clip the action, so the sent action is the action that we input to the robot.
        _sent_action = robot.send_action(robot_action_to_send)

        # Write to dataset
        if dataset is not None:
            action_frame = build_dataset_frame(
                dataset.features, action_values, prefix=ACTION
            )
            frame = {**observation_frame, **action_frame, "task": single_task}
            dataset.add_frame(frame)

        if display_data:
            log_rerun_data(observation=obs_processed, action=action_values)

        dt_s = time.perf_counter() - start_loop_t
        busy_wait(1 / fps - dt_s)

        timestamp = time.perf_counter() - start_episode_t


@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    init_logging()
    logging.info(pformat(asdict(cfg)))
    if cfg.display_data:
        init_rerun(session_name="recording")

    robot = make_robot_from_config(cfg.robot)
    teleop = (
        make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None
    )

    teleop_action_processor, robot_action_processor, robot_observation_processor = (
        make_default_processors()
    )

    dataset_features = combine_feature_dicts(
        aggregate_pipeline_dataset_features(
            pipeline=teleop_action_processor,
            initial_features=create_initial_features(
                action=robot.action_features
            ),  # TODO(steven, pepijn): in future this should be come from teleop or policy
            use_videos=cfg.dataset.video,
        ),
        aggregate_pipeline_dataset_features(
            pipeline=robot_observation_processor,
            initial_features=create_initial_features(
                observation=robot.observation_features
            ),
            use_videos=cfg.dataset.video,
        ),
    )

    if cfg.resume:
        dataset = LeRobotDataset(
            cfg.dataset.repo_id,
            root=cfg.dataset.root,
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
        )

        if hasattr(robot, "cameras") and len(robot.cameras) > 0:
            dataset.start_image_writer(
                num_processes=cfg.dataset.num_image_writer_processes,
                num_threads=cfg.dataset.num_image_writer_threads_per_camera
                * len(robot.cameras),
            )
        sanity_check_dataset_robot_compatibility(
            dataset, robot, cfg.dataset.fps, dataset_features
        )
    else:
        # Create empty dataset or load existing saved episodes
        sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
        dataset = LeRobotDataset.create(
            cfg.dataset.repo_id,
            cfg.dataset.fps,
            root=cfg.dataset.root,
            robot_type=robot.name,
            features=dataset_features,
            use_videos=cfg.dataset.video,
            image_writer_processes=cfg.dataset.num_image_writer_processes,
            image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera
            * len(robot.cameras),
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
        )

    use_openvino = cfg.openvino_model_path is not None

    # Load pretrained policy if required for PyTorch inference
    policy = None
    if cfg.policy is not None and not use_openvino:
        policy = make_policy(cfg.policy, ds_meta=dataset.meta)

    preprocessor = None
    postprocessor = None
    if cfg.policy is not None:
        if use_openvino and cfg.policy.device != "cpu":
            logging.info(
                "OpenVINO inference runs on CPU inputs. Overriding policy device '%s' to 'cpu' for preprocessing.",
                cfg.policy.device,
            )
            cfg.policy.device = "cpu"
        preprocessor, postprocessor = make_pre_post_processors(
            policy_cfg=cfg.policy,
            pretrained_path=cfg.policy.pretrained_path,
            dataset_stats=rename_stats(dataset.meta.stats, cfg.dataset.rename_map),
            preprocessor_overrides={
                "device_processor": {"device": cfg.policy.device},
                "rename_observations_processor": {"rename_map": cfg.dataset.rename_map},
            },
        )

    ov_session = None
    if use_openvino:
        if cfg.policy is None:
            raise ValueError(
                "An ACT policy configuration is required when using OpenVINO inference."
            )
        core = ov.Core()
        print("Available OpenVINO devices:", core.available_devices)

        if cfg.openvino_device.upper() in core.available_devices:
            logging.info(
                "Using OpenVINO device: %s", cfg.openvino_device.upper()
            )
        else:
            logging.warning(
                "Requested OpenVINO device '%s' is not available. Available devices: %s. Falling back to CPU.",
                cfg.openvino_device.upper(),
                ", ".join(core.available_devices),
            )
            cfg.openvino_device = "CPU"

        # TODO: allow user to configure the n_action_steps
        # action_chunk_size = getattr(cfg.policy, "n_action_steps", 1)
        action_chunk_size = 50
        print(f"Action chunk size is set to {action_chunk_size}. Please configure in inference.py if required.")

        ov_session = OpenVINOInference(
            model_path=cfg.openvino_model_path,
            device=cfg.openvino_device,
            enable_npu_high_precision=cfg.openvino_enable_npu_high_precision,
            action_chunk_size=action_chunk_size,
            input_features=dataset.features,
            rename_map=cfg.dataset.rename_map,
        )

    robot.connect()
    if teleop is not None:
        teleop.connect()

    listener, events = init_keyboard_listener()

    try:
        with VideoEncodingManager(dataset):
            recorded_episodes = 0
            while (
                recorded_episodes < cfg.dataset.num_episodes
                and not events["stop_recording"]
            ):
                log_say(f"Recording episode {dataset.num_episodes}", cfg.play_sounds)
                record_loop(
                    robot=robot,
                    events=events,
                    fps=cfg.dataset.fps,
                    teleop_action_processor=teleop_action_processor,
                    robot_action_processor=robot_action_processor,
                    robot_observation_processor=robot_observation_processor,
                    teleop=teleop,
                    policy=policy,
                    ov_session=ov_session,
                    preprocessor=preprocessor,
                    postprocessor=postprocessor,
                    dataset=dataset,
                    control_time_s=cfg.dataset.episode_time_s,
                    single_task=cfg.dataset.single_task,
                    display_data=cfg.display_data,
                )

                # Execute a few seconds without recording to give time to manually reset the environment
                # Skip reset for the last episode to be recorded
                if not events["stop_recording"] and (
                    (recorded_episodes < cfg.dataset.num_episodes - 1)
                    or events["rerecord_episode"]
                ):
                    log_say("Reset the environment", cfg.play_sounds)
                    record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        teleop_action_processor=teleop_action_processor,
                        robot_action_processor=robot_action_processor,
                        robot_observation_processor=robot_observation_processor,
                        teleop=teleop,
                        ov_session=None,
                        control_time_s=cfg.dataset.reset_time_s,
                        single_task=cfg.dataset.single_task,
                        display_data=cfg.display_data,
                    )

                if events["rerecord_episode"]:
                    log_say("Re-record episode", cfg.play_sounds)
                    events["rerecord_episode"] = False
                    events["exit_early"] = False
                    dataset.clear_episode_buffer()
                    continue

                dataset.save_episode()
                recorded_episodes += 1

        log_say("Stop recording", cfg.play_sounds, blocking=True)

    except KeyboardInterrupt:
        print("Keyboard interrupt detected. Exiting ...")

    robot.disconnect()
    if teleop is not None:
        teleop.disconnect()

    if not is_headless() and listener is not None:
        listener.stop()

    log_say("Exiting", cfg.play_sounds)
    return dataset


def main():
    register_third_party_devices()
    record()


if __name__ == "__main__":
    main()
