// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

import { useMutation, useQuery } from '@tanstack/react-query'

const BASE_URL = '/api/synthetic-image-generation'

export enum GenerationType {
  GOOD_DATASET = 'good_dataset',
  MISSING_COMPONENTS = 'missing_components',
  CUSTOM = 'custom',
}

function base64ToBlob(base64: string): Blob {
  const byteString = atob(base64)
  const arrayBuffer = new ArrayBuffer(byteString.length)
  const uint8Array = new Uint8Array(arrayBuffer)
  for (let i = 0; i < byteString.length; i++) {
    uint8Array[i] = byteString.charCodeAt(i)
  }
  return new Blob([uint8Array], { type: 'image/png' })
}

function validateProjectName(name: string): void {
  if (!name || !/^[a-zA-Z0-9_\-\s]+$/.test(name)) {
    throw new Error('Invalid project name: must be alphanumeric')
  }
}

export function useGetSyntheticImageHistory(enabled = true) {
  return useQuery({
    queryKey: ['synthetic-image-history'],
    queryFn: async () => {
      const url = new URL(
        `${BASE_URL}/image-gen/history`,
        window.location.origin,
      )
      const res = await fetch(url)
      if (!res.ok) throw new Error('Failed to fetch image history')
      const data = await res.json()
      return data.images.map(
        (filename: string) => `${BASE_URL}/outputs/${filename}`,
      ) as string[]
    },
    enabled,
  })
}

export function useGetSyntheticImageProjects(enabled = true) {
  return useQuery({
    queryKey: ['synthetic-image-projects'],
    queryFn: async () => {
      const url = new URL(`${BASE_URL}/projects`, window.location.origin)
      const res = await fetch(url)
      if (!res.ok) throw new Error('Failed to fetch projects')
      const data = await res.json()
      return (data.projects || []) as string[]
    },
    enabled,
  })
}

export function useGenerateSyntheticImage() {
  return useMutation({
    mutationFn: async ({
      baseImage64,
      type,
      objective,
      customPrompt,
      customType,
      projectName = 'default',
    }: {
      baseImage64: string
      type: GenerationType
      objective?: string
      customPrompt?: string
      customType?: string
      projectName?: string
    }) => {
      const blob = base64ToBlob(baseImage64)
      const formData = new FormData()
      formData.append('file', blob, 'image.png')

      let backendType = 'SYNTHETIC'
      if (type === GenerationType.MISSING_COMPONENTS)
        backendType = 'MISSING_COMPONENT'
      else if (type === GenerationType.CUSTOM) backendType = 'CUSTOM'

      formData.append('generation_type', backendType)
      if (objective) formData.append('objective', objective)
      if (customPrompt) formData.append('custom_prompt', customPrompt)
      if (customType) formData.append('custom_type', customType)
      formData.append('project_name', projectName)

      const url = new URL(
        `${BASE_URL}/image-gen/generate`,
        window.location.origin,
      )
      const res = await fetch(url, {
        method: 'POST',
        body: formData,
      })
      if (!res.ok) {
        const text = await res.text()
        throw new Error(text || 'Image generation failed')
      }
      const data = await res.json()

      if (!data.image) {
        throw new Error('No image returned from API')
      }

      const imageUrl = `${BASE_URL}/outputs/${data.image}`

      let finalPrompt = 'Variation generated by backend'
      if (type === GenerationType.MISSING_COMPONENTS) {
        finalPrompt = objective
          ? `Completing objective: ${objective}`
          : 'Completing objective'
      } else if (type === GenerationType.CUSTOM) {
        finalPrompt = customPrompt || 'Custom generation'
      }

      return { imageUrls: [imageUrl], finalPrompt }
    },
  })
}

export function useDeleteSyntheticImageAsset() {
  return useMutation({
    mutationFn: async (filename: string) => {
      const url = new URL(
        `${BASE_URL}/image-gen/delete/${encodeURIComponent(filename)}`,
        window.location.origin,
      )
      const res = await fetch(url, { method: 'DELETE' })
      if (!res.ok) throw new Error('Failed to delete asset')
    },
  })
}

export function useCreateSyntheticImageProject() {
  return useMutation({
    mutationFn: async (name: string) => {
      const formData = new FormData()
      formData.append('project_name', name)
      const url = new URL(`${BASE_URL}/projects/create`, window.location.origin)
      const res = await fetch(url, {
        method: 'POST',
        body: formData,
      })
      if (!res.ok) throw new Error('Failed to create project')
      const data = await res.json()
      return data.project_name as string
    },
  })
}

export function useDeleteSyntheticImageProject() {
  return useMutation({
    mutationFn: async (name: string) => {
      validateProjectName(name)
      const url = new URL(
        `${BASE_URL}/projects/delete/${encodeURIComponent(name)}`,
        window.location.origin,
      )
      const res = await fetch(url, { method: 'DELETE' })
      if (!res.ok) throw new Error('Failed to delete project')
    },
  })
}

export function useExportSyntheticImageProject() {
  return useMutation({
    mutationFn: async (name: string) => {
      validateProjectName(name)
      const url = new URL(
        `${BASE_URL}/projects/export/${encodeURIComponent(name)}`,
        window.location.origin,
      )
      const res = await fetch(url)
      if (!res.ok) throw new Error('Failed to export project')

      const blob = await res.blob()
      const objectUrl = window.URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = objectUrl
      a.download = `${name}.zip`
      document.body.appendChild(a)
      a.click()
      window.URL.revokeObjectURL(objectUrl)
      document.body.removeChild(a)
    },
  })
}
