# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

import os
import sys
import signal
import threading
import asyncio
import time
import socket
from pathlib import Path
from mcp.server.fastmcp import FastMCP

# Message templates
SERVER_MESSAGES = {
    'server_start': 'data_analysis_server MCP server starting' + (' on port {port}'),
    'server_started': 'data_analysis_server MCP server started successfully' + (' on port {port}'),
    'server_stopped': 'data_analysis_server MCP server stopped',
    'server_start_fail': 'Failed to start data_analysis_server MCP server',
    'server_already_running': 'Server is already running',
    'server_not_running': 'Server is not running',
    'server_error': 'Server error: {error}',
    'start_error': 'Error starting server: {error}',
    'stop_error': 'Error stopping server: {error}',
    'stop_success': 'Server stopped successfully',
    'stop_fail': 'Server failed to stop',
    'status_running': 'data_analysis_server MCP server is running',
    'status_stopped': 'data_analysis_server MCP server is not running',
    'ping_success': 'Server is responding',
    'ping_fail': 'Server is not responding',
    'interrupt': 'Operation cancelled by user',
    'error': 'Error: {error}',
    'version': 'data_analysis_server MCP Server v{version}',
}

def format_message(key: str, **kwargs) -> str:
    """Format a server message with given parameters."""
    template = SERVER_MESSAGES.get(key, '')
    return template.format(**kwargs) if template else ''

def create_response(success, message, data=None, exit_code=0, current_port=None, current_protocol=None):
    """Create a standardized JSON response"""
    response = {
        "success": success,
        "message": message,
        "timestamp": int(time.time()),
        "protocol": current_protocol or data_analysis_server_PROTOCOL,
    }
    if current_protocol != 'stdio' and current_port is not None:
        response["port"] = current_port
    if data:
        response["data"] = data
    return response, exit_code

# Initialize FastMCP server
# Generated by McpServerGen.py on 2025-11-25 14:08:56
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
data_analysis_server_PORT = int(os.getenv('MCP_DATA_ANALYSIS_SERVER_PORT', 7905))
data_analysis_server_PROTOCOL = os.getenv('MCP_DATA_ANALYSIS_SERVER_PROTOCOL', 'http')
mcp = None  # Will be initialized after command line parsing

# Global variables for server management
_server_thread = None
_server_loop = None
_server_running = False
_server_start_time = None

#### Server Tools ####

async def analyze_data(
    data,
    analysis_question: str = "What are the key insights and patterns in this data?",
    analysis_type: str = "comprehensive"
) -> str:
    """Analyze data using AI/LLM to extract insights, patterns, and recommendations.
    
    This tool receives JSON data from database queries and performs intelligent analysis
    using a local LLM (llama.cpp). It provides key findings, patterns, and actionable recommendations.
    
    Workflow:
    1. Receives JSON data from query_database tool (from odbcserver)
    2. Parses and converts to DataFrame for analysis
    3. Generates statistical summaries and distributions
    4. Sends to LLM for intelligent interpretation
    5. Returns formatted analysis report
    
    Args:
        data: JSON string or dict from database query, can be single or multiple datasets
        analysis_question: Specific question to focus the analysis
        analysis_type: "comprehensive", "statistical", "trends", or "recommendations"
    
    Returns:
        str: Formatted analysis report with insights and recommendations
    """
    try:
        import os
        import time
        import json
        import pandas as pd
        
        # === ADD DETAILED DEBUG LOGGING ===
        log_path = os.path.join(os.path.dirname(__file__), "debug.log")
        try:
            with open(log_path, "a", encoding="utf-8") as f:
                f.write(f"\n{'='*60}\n")
                f.write(f"analyze_data called at {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
                f.write(f"Data type: {type(data)}\n")
                f.write(f"Data repr (first 500 chars): {repr(data)[:500]}\n")
                
                # Check if it's already parsed
                if isinstance(data, (dict, list)):
                    f.write("✓ Data is already parsed (dict or list)\n")
                    parsed_data = data  # No need to parse
                elif isinstance(data, str):
                    f.write(f"Data is a string, length: {len(data)}\n")
                    f.write(f"First 200 chars: {data[:200]}\n")
                    # Try to parse
                    try:
                        parsed_data = json.loads(data)
                        f.write("✓ Successfully parsed JSON string\n")
                    except json.JSONDecodeError as e:
                        f.write(f"✗ JSON parse error: {e}\n")
                        f.write(f"Error at position: {e.pos}\n")
                        f.write(f"Context: {data[max(0, e.pos-50):e.pos+50]}\n")
                        raise
                else:
                    f.write(f"✗ Unexpected data type: {type(data)}\n")
                    parsed_data = data
                
                f.write(f"{'='*60}\n")
        except Exception as log_error:
            print(f"Debug logging failed: {log_error}")
        
        # === SIMPLIFIED PARSING LOGIC ===
        # Check type first
        if isinstance(data, str):
            try:
                parsed_data = json.loads(data)
            except json.JSONDecodeError as e:
                return f"Error: Invalid JSON at position {e.pos}\n\nReceived: {data[:500]}\n\nError: {str(e)}"
        else:
            # Already parsed by MCP framework
            parsed_data = data
        
        # Rest of your analysis code...
        # Check if we have multiple datasets
        is_multiple = (
            isinstance(parsed_data, dict) and
            "_metadata" in parsed_data and
            "separate_tables" in parsed_data["_metadata"]
        )
        
        if is_multiple:
            return await _analyze_multiple_datasets(parsed_data, analysis_question, analysis_type, log_path)
        else:
            return await _analyze_single_dataset(parsed_data, analysis_question, analysis_type, log_path)
            
    except Exception as e:
        import traceback
        error_details = traceback.format_exc()
        return f"Error analyzing data: {str(e)}\n\nDetails:\n{error_details}"


async def _analyze_single_dataset(data, analysis_question, analysis_type, log_path):
    """Analyze a single dataset."""
    import pandas as pd
    import json
    import os
    
    # Convert to DataFrame
    try:
        if isinstance(data, list):
            df = pd.DataFrame(data)
        elif isinstance(data, dict):
            # Check if it's column-oriented (dict of lists)
            if all(isinstance(v, list) for v in data.values()):
                df = pd.DataFrame(data)
            else:
                # Single record
                df = pd.DataFrame([data])
        else:
            return f"Error: Cannot convert data type {type(data)} to DataFrame"
    except Exception as e:
        return f"Error creating DataFrame: {str(e)}"
    
    if df.empty:
        return "Error: No data to analyze (empty dataset)"
    
    # Get analysis from LLM
    analysis_text = await _get_llm_analysis(df, analysis_question, analysis_type)
    
    # Format output
    report = f"""{'='*60}
DATA ANALYSIS REPORT
{'='*60}

Dataset Overview:
- Rows: {len(df)}
- Columns: {len(df.columns)}
- Analysis Type: {analysis_type}

Question: {analysis_question}

{'='*60}
RAW DATA
{'='*60}

{df.to_string(index=False)}

{'='*60}
ANALYSIS
{'='*60}

{analysis_text}

{'='*60}
"""
    return report


async def _analyze_multiple_datasets(data, analysis_question, analysis_type, log_path):
    """Analyze multiple datasets from query_database."""
    import pandas as pd
    import json
    import os
    
    metadata = data.get("_metadata", {})
    total_results = metadata.get("total_results", 0)
    
    # Build comprehensive report
    report = f"""{'='*60}
MULTI-DATASET ANALYSIS REPORT
{'='*60}

Overview:
- Total Datasets: {total_results}
- Analysis Type: {analysis_type}
- Question: {analysis_question}

"""
    
    # Collect all datasets
    datasets = []
    for key in sorted(data.keys()):
        if key.startswith("result_"):
            result_data = data[key]
            try:
                # result_data is a list of dicts (records)
                df = pd.DataFrame(result_data)
                datasets.append((key, df))
            except Exception as e:
                report += f"\n⚠ Error processing {key}: {str(e)}\n"
                continue
    
    if not datasets:
        return report + "\nError: No valid datasets found to analyze."
    
    # Show raw data for each dataset
    report += f"{'='*60}\n"
    report += "RAW DATA\n"
    report += f"{'='*60}\n\n"
    
    for idx, (key, df) in enumerate(datasets, 1):
        report += f"\n--- Dataset {idx} ({key}) ---\n"
        report += f"Rows: {len(df)}, Columns: {len(df.columns)}\n"
        report += f"Columns: {', '.join(df.columns.tolist())}\n\n"
        report += df.to_string(index=False) + "\n"
    
    # Combined analysis
    report += f"\n{'='*60}\n"
    report += "ANALYSIS\n"
    report += f"{'='*60}\n\n"
    
    # If only one dataset, just analyze it
    if len(datasets) == 1:
        analysis = await _get_llm_analysis(datasets[0][1], analysis_question, analysis_type)
        report += analysis + "\n"
    else:
        # Multiple datasets - analyze each individually
        for idx, (key, df) in enumerate(datasets, 1):
            report += f"\n--- Analysis of Dataset {idx} ({key}) ---\n\n"
            individual_analysis = await _get_llm_analysis(
                df, 
                f"{analysis_question} (Focus on dataset {idx})",
                analysis_type
            )
            report += individual_analysis + "\n"
        
        # Add cross-dataset insights
        report += f"\n{'-'*60}\n"
        report += "CROSS-DATASET INSIGHTS\n"
        report += f"{'-'*60}\n\n"
        
        # Create summary for cross-analysis
        summary_text = f"Analyzing {len(datasets)} related datasets:\n\n"
        for idx, (key, df) in enumerate(datasets, 1):
            summary_text += f"Dataset {idx} ({key}):\n"
            summary_text += f"  - {len(df)} rows, {len(df.columns)} columns\n"
            summary_text += f"  - Columns: {', '.join(df.columns.tolist())}\n"
            summary_text += f"  - Sample: {df.head(2).to_dict('records')}\n\n"
        
        cross_analysis = await _get_llm_analysis(
            datasets[0][1],  # Use first dataset as context
            f"Cross-dataset analysis: {analysis_question}\n\nContext:\n{summary_text}",
            analysis_type
        )
        report += cross_analysis + "\n"
    
    report += f"\n{'='*60}\n"
    return report


async def _get_llm_analysis(df: 'pd.DataFrame', question: str, analysis_type: str) -> str:
    """Get AI analysis from LLM for a single DataFrame."""
    import pandas as pd
    import os
    
    try:
        import openai
        base_url = os.getenv("LLAMA_CPP_URL", "http://127.0.0.1:8080/v1")
        client = openai.OpenAI(
            base_url=base_url,
            api_key=""  # No API key needed for local llama.cpp
        )
    except ImportError:
        return "Error: openai package not installed. Run: pip install openai"
    
    # Prepare data summary
    summary_parts = []
    summary_parts.append(f"Dataset: {df.shape[0]} rows × {df.shape[1]} columns")
    summary_parts.append(f"Columns: {', '.join(df.columns)}\n")
    
    # Sample data
    max_rows = min(30, len(df))
    if len(df) > max_rows:
        summary_parts.append(f"First {max_rows} rows:")
        summary_parts.append(df.head(max_rows).to_string(index=False))
        summary_parts.append(f"\n... {len(df) - max_rows} more rows not shown")
    else:
        summary_parts.append("All data:")
        summary_parts.append(df.to_string(index=False))
    
    # Numeric statistics
    numeric_cols = df.select_dtypes(include=['number']).columns
    if len(numeric_cols) > 0:
        summary_parts.append("\n\nNumeric Statistics:")
        summary_parts.append(df[numeric_cols].describe().to_string())
    
    # Categorical distributions
    categorical_cols = df.select_dtypes(include=['object']).columns
    for col in categorical_cols:
        if df[col].nunique() <= 15:
            summary_parts.append(f"\n\n{col} distribution:")
            summary_parts.append(df[col].value_counts().to_string())
    
    data_summary = "\n".join(summary_parts)
    
    # Customize prompt based on analysis type
    if analysis_type == "statistical":
        focus = "Focus on statistical measures, distributions, averages, and outliers."
    elif analysis_type == "trends":
        focus = "Focus on trends, patterns over time, growth rates, and directional insights."
    elif analysis_type == "recommendations":
        focus = "Focus on actionable business recommendations and strategic suggestions."
    else:  # comprehensive
        focus = "Provide a comprehensive analysis covering all aspects."
    
    system_prompt = f"""You are an expert data analyst. Analyze the provided data and deliver actionable insights.

{focus}

Structure your analysis with:
1. **Key Findings**: Most important discoveries
2. **Statistical Observations**: Notable numbers and patterns
3. **Trends & Patterns**: What the data reveals
4. **Anomalies**: Unusual or unexpected findings (if any)
5. **Business Recommendations**: Actionable next steps

Be concise, clear, data-driven, and business-focused."""
    
    user_prompt = f"""Data to analyze:

{data_summary}

Analysis Question: {question}

Provide your analysis:"""
    
    # Call LLM
    try:
        response = client.chat.completions.create(
            model="local-model",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.3,
        )
        
        return response.choices[0].message.content.strip()
        
    except Exception as e:
        return f"Error calling LLM: {str(e)}\n\nMake sure llama.cpp server is running at {base_url}"



#### Tool Registration ####

# List of all tool functions to register
TOOL_FUNCTIONS = [
    analyze_data,
    # Add additional tool functions here
]

def register_tools(verbose=True):
    """Register all tools with the MCP server."""
    global mcp
    if mcp is None:
        raise RuntimeError("MCP instance must be initialized before registering tools")
    
    for tool_func in TOOL_FUNCTIONS:
        mcp.tool()(tool_func)
        if verbose:
            print(f"Registered tool: {tool_func.__name__}")

#### Server management functions ####

def _run_server_in_thread(port, protocol):
    """Run the MCP server in a separate thread."""
    global _server_loop, _server_running
    
    _server_loop = asyncio.new_event_loop()
    asyncio.set_event_loop(_server_loop)
    
    try:
        _server_running = True
        if protocol == 'stdio':
            print(format_message('server_start'))
        else:
            print(format_message('server_start', port=port))
        mcp.run(transport="streamable-http" if protocol == "http" else protocol)
    except Exception as e:
        print(format_message('server_error', error=str(e)))
    finally:
        _server_running = False

def start_server(port=None, protocol=None):
    """Start the MCP server in a separate thread."""
    global _server_thread, _server_running, _server_start_time, mcp
    
    # Use provided parameters or fall back to global defaults
    if port is None:
        port = data_analysis_server_PORT
    if protocol is None:
        protocol = data_analysis_server_PROTOCOL
    
    # For stdio protocol, we don't need a port
    if protocol == 'stdio':
        port = None
    
    if (protocol == 'stdio' and mcp is None) or (protocol != 'stdio' and port != data_analysis_server_PORT):
        # Create fresh FastMCP instance with current port and protocol
        if protocol == 'stdio':
            mcp = FastMCP("data_analysis_server")
        else:
            mcp = FastMCP("data_analysis_server", port=port)
        # Register all tools with the new instance
        register_tools()
        
    try:
        # Check if server is already running
        if _server_running:
            print(format_message('server_already_running'))
            return False

        _server_thread = threading.Thread(target=_run_server_in_thread, args=(port, protocol), daemon=True)
        _server_thread.start()
        
        # Start shutdown listener in a separate daemon thread (only for non-stdio protocols)
        if protocol != 'stdio' and port is not None:
            threading.Thread(target=shutdown_listener, args=(port,), daemon=True).start()
        
        _server_start_time = time.time()
        
        time.sleep(2)  # Wait for server to start
        if _server_running:
            if protocol == 'stdio':
                print(format_message('server_started'))
            else:
                print(format_message('server_started', port=port))
            return True
        else:
            print(format_message('server_start_fail'))
            return False
    except Exception as e:
        print(format_message('start_error', error=str(e)))
        return False

def stop_server(json_mode=False, port=None):
    """Stop the MCP server using multiple reliable methods."""
    global _server_thread, _server_loop, _server_running

    # Use provided port or fall back to global default
    if port is None:
        port = data_analysis_server_PORT
    
    # For stdio protocol, port is None
    if data_analysis_server_PROTOCOL == 'stdio':
        port = None
    
    # First try to stop server started by this process
    if _server_running:
        try:
            _server_running = False
            
            # More aggressive shutdown
            if _server_loop and _server_loop.is_running():
                # Stop all running tasks in the loop
                for task in asyncio.all_tasks(_server_loop):
                    task.cancel()
                _server_loop.call_soon_threadsafe(_server_loop.stop)
            
            if _server_thread and _server_thread.is_alive():
                _server_thread.join(timeout=10)  # Increased timeout
                
            # Force kill thread if it's still alive
            if _server_thread and _server_thread.is_alive():
                # Reset thread reference
                _server_thread = None
        except Exception as e:
            print(format_message('stop_error', error=str(e)))
    
    # Try multiple shutdown methods for cross-process termination (skip for stdio)
    shutdown_success = False
    current_port = port
    
    # Skip port-based shutdown methods for stdio protocol
    if current_port is not None:
        # Method 1: Try graceful shutdown via control socket
        if not shutdown_success:
            try:
                with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
                    s.settimeout(5)
                    s.connect(('127.0.0.1', current_port + 1))
                    s.sendall(b'SHUTDOWN')
                    resp = s.recv(1024)
                    if resp == b'OK':
                        shutdown_success = True
                        if not json_mode:
                            print("Server stopped successfully via shutdown listener")
            except (ConnectionRefusedError, OSError, socket.timeout):
                # Shutdown listener is not accessible, try other methods
                pass
    
        # Method 2: Try to kill process using psutil (if available)
        if not shutdown_success and current_port is not None:
            try:
                import psutil
                killed_processes = []
                
                for proc in psutil.process_iter(['pid', 'name', 'cmdline']):
                    try:
                        # Look for Python processes running this server
                        if proc.info['name'] and 'python' in proc.info['name'].lower():
                            cmdline = proc.info['cmdline']
                            # More specific check: look for 'server.py' and server name in command line
                            if (cmdline and 
                                any('server.py' in str(arg) for arg in cmdline) and 
                                any('data_analysis_server' in str(arg).lower() for arg in cmdline)):
                                # Check if this process is using our port
                                try:
                                    for conn in proc.net_connections():
                                        if conn.laddr.port == current_port:
                                            proc.terminate()
                                            killed_processes.append(proc.info['pid'])
                                            break
                                except (psutil.AccessDenied, psutil.NoSuchProcess):
                                    continue
                    except (psutil.NoSuchProcess, psutil.AccessDenied):
                        continue
                
                if killed_processes:
                    # Wait a moment for processes to terminate
                    time.sleep(2)
                    if not is_port_in_use(current_port):
                        shutdown_success = True
                        if not json_mode:
                            print(f"Server stopped successfully (killed processes: {killed_processes})")
            except ImportError:
                # psutil not available, fall back to other methods
                pass
        
        # Method 3: Try netstat + taskkill (Windows specific)
        if not shutdown_success and current_port is not None and os.name == 'nt':
            try:
                # Import subprocess only on Windows where this branch runs
                import subprocess  # nosec B404 - Windows-only, safe usage; no shell=True used here
                # Find process ID using netstat - safer without shell=True
                # Use PowerShell instead of shell pipeline for better security
                ps_command = f'netstat -ano | Select-String ":{current_port}"'
                result = subprocess.run(
                    ['powershell', '-Command', ps_command],
                    capture_output=True,
                    text=True,
                    shell=False  # ✓ More secure
                )
                
                if result.returncode == 0 and result.stdout.strip():
                    lines = result.stdout.strip().split('\n')
                    pids = set()
                    for line in lines:
                        parts = line.split()
                        if len(parts) >= 5:
                            pids.add(parts[-1])
                    
                    # Kill the processes
                    for pid in pids:
                        try:
                            subprocess.run(['taskkill', '/PID', pid, '/F'],  # nosec B603 - PID from netstat output
                                         capture_output=True, check=True)
                        except:
                            continue
                    
                    # Wait and check if port is free
                    time.sleep(2)
                    if not is_port_in_use(current_port):
                        shutdown_success = True
                        if not json_mode:
                            print(f"Server stopped successfully (killed PIDs: {', '.join(pids)})")
            except Exception:
                pass
    
    # For protocols with ports, wait for port to be released
    if current_port is not None:
        max_wait = 5
        wait_count = 0
        while is_port_in_use(current_port) and wait_count < max_wait:
            time.sleep(1)
            wait_count += 1
    
    # Check if server is actually stopped
    if current_port is None:  # stdio protocol
        # For stdio, just check if the internal process stopped
        if not _server_running:
            if not json_mode:
                print(format_message('server_stopped'))
            return True
        else:
            if not json_mode:
                print(format_message('stop_fail'))
            return False
    elif not is_port_in_use(current_port):  # port-based protocols
        if not json_mode:
            print(format_message('server_stopped'))
        return True
    else:
        if shutdown_success:
            if not json_mode:
                print(format_message('server_stopped'))
            return True
        else:
            if not json_mode:
                print(format_message('stop_fail'))
            return False

def is_server_running():
    """Check if the server is currently running."""
    # For stdio protocol, only check the internal flag since there's no port
    if data_analysis_server_PROTOCOL == 'stdio':
        return _server_running
    # For other protocols, check both internal flag and port usage for more accurate status
    return _server_running and is_port_in_use(data_analysis_server_PORT)

def is_port_in_use(port):
    """Check if a port is currently in use."""
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(1)  # Add timeout to avoid hanging
            result = s.connect_ex(('127.0.0.1', port))
            return result == 0
    except Exception:
        return False

def shutdown_listener(port):
    """Listen for a shutdown command on a local TCP socket."""
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    try:
        # Allow socket reuse to prevent "Address already in use" errors
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        sock.bind(('127.0.0.1', port + 1))  # Use port + 1 for control
        sock.listen(1)
        sock.settimeout(1)  # Add timeout to make it responsive
        
        while _server_running:
            try:
                conn, addr = sock.accept()
                data = conn.recv(1024)
                if data == b'SHUTDOWN':
                    print("Shutdown command received via control socket")
                    stop_server(json_mode=False, port=port)  # Pass the port parameter
                    conn.sendall(b'OK')
                    conn.close()
                    break
                conn.close()
            except socket.timeout:
                # Continue loop to check _server_running flag
                continue
            except Exception:
                # Handle any other socket errors gracefully
                break
    except Exception as e:
        # Port might be in use or other socket error
        print(f"Shutdown listener could not start: {e}")
        # Continue without shutdown listener - other methods will still work
    finally:
        try:
            sock.close()
        except:
            pass

# Command line interface
if __name__ == "__main__":
    import json
    import argparse

    class ArgumentParserWithExceptions(argparse.ArgumentParser):
        def error(self, message):
            raise ValueError(message)
    
    def print_response(response, exit_code, json_output=False):
        """Print response and exit"""
        if json_output:
            print(json.dumps(response), flush=True)
        else:
            print(response["message"])
        sys.stdout.flush() 
        sys.exit(exit_code)
    
    # Set up argument parser
    parser = ArgumentParserWithExceptions(
        description="Analysis API MCP",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python server.py start
  python server.py start --json
  python server.py stop
  python server.py status --json
  python server.py ping
  python server.py version
        """
    )
    
    parser.add_argument("command", choices=["start", "stop", "status", "ping", "version", "help"])
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--timeout", type=int, default=30)
    parser.add_argument("--port", type=int)
    parser.add_argument("--protocol", choices=["sse", "stdio", "http"], help="Communication protocol")
    
    try:
        args = parser.parse_args()
        
        current_port = data_analysis_server_PORT
        current_protocol = data_analysis_server_PROTOCOL
        if args.port:
            current_port = args.port
            os.environ[f'MCP_DATA_ANALYSIS_SERVER_PORT'] = str(current_port)
        if args.protocol:
            current_protocol = args.protocol
            os.environ[f'MCP_DATA_ANALYSIS_SERVER_PROTOCOL'] = current_protocol
        
        # For stdio protocol, ignore port setting
        if current_protocol == 'stdio':
            current_port = None
            
        # Initialize FastMCP with the final port and protocol values
        if current_protocol == 'stdio':
            mcp = FastMCP("data_analysis_server")
        else:
            mcp = FastMCP("data_analysis_server", port=current_port)
        # Register all tools with the MCP instance
        register_tools(verbose=not args.json)      
            
        if args.command == "start":
            if start_server(current_port, current_protocol):
                if current_protocol == 'stdio':
                    response, exit_code = create_response(
                        True, 
                        format_message('server_started'),
                        {},
                        exit_code=0 if _server_running else 1,
                        current_port=current_port,
                        current_protocol=current_protocol
                    )
                else:
                    response, exit_code = create_response(
                        True, 
                        format_message('server_started', port=current_port),
                        {"port": current_port},
                        exit_code=0 if _server_running else 1,
                        current_port=current_port,
                        current_protocol=current_protocol
                    )
                
                if args.json:
                    print(json.dumps(response), flush=True)
        
                try:
                    while _server_running:
                        time.sleep(1)
                except KeyboardInterrupt:
                    print("\\nReceived interrupt signal")
                    stop_server(json_mode=args.json, port=current_port)
                    response, exit_code = create_response(
                        True, 
                        format_message('interrupt'),
                        current_port=current_port,
                        current_protocol=current_protocol
                    )
            else:
                response, exit_code = create_response(
                    False, 
                    format_message('server_start_fail'), 
                    exit_code=1,
                    current_port=current_port,
                    current_protocol=current_protocol
                )
                
        elif args.command == "stop":
            success = stop_server(json_mode=args.json, port=current_port)
            response, exit_code = create_response(
                success,
                format_message('stop_success' if success else 'stop_fail'),
                exit_code=0 if success else 1,
                current_port=current_port,
                current_protocol=current_protocol
            )
            
        elif args.command == "status":
            # For command line usage, check appropriate method based on protocol
            if current_protocol == 'stdio':
                # For stdio, we can't easily check if another process is running
                # so we'll just report based on what we can detect
                running = False  # Default to not running for separate process
                status_data = {"status": "running" if running else "stopped", "protocol": current_protocol}
            else:
                running = is_port_in_use(current_port)
                status_data = {"status": "running" if running else "stopped", "port": current_port, "protocol": current_protocol}
            
            msg_key = 'status_running' if running else 'status_stopped'
            response, exit_code = create_response(
                running,
                format_message(msg_key),
                status_data,
                0 if running else 1,
                current_port=current_port,
                current_protocol=current_protocol
            )
            
        elif args.command == "ping":
            # For command line usage, check appropriate method based on protocol
            if current_protocol == 'stdio':
                # For stdio, we can't easily ping another process
                running = False  # Default to not running for separate process
                ping_data = {"status": "healthy" if running else "unhealthy", "protocol": current_protocol}
            else:
                running = is_port_in_use(current_port)
                ping_data = {"status": "healthy" if running else "unhealthy", "port": current_port, "protocol": current_protocol}
            
            msg_key = 'ping_success' if running else 'ping_fail'
            response, exit_code = create_response(
                running,
                format_message(msg_key),
                ping_data,
                0 if running else 1,
                current_port=current_port,
                current_protocol=current_protocol
            )
            
        elif args.command == "version":
            import platform
            version_info = {
                "version": "1.0.0",
                "python_version": platform.python_version(),
                "platform": platform.platform(),
                "protocol": current_protocol
            }
            if current_protocol != 'stdio' and current_port is not None:
                version_info["port"] = current_port
            response, exit_code = create_response(
                True, 
                format_message('version', version=version_info['version']), 
                version_info,
                current_port=current_port,
                current_protocol=current_protocol
            )
            
        elif args.command == "help":
            parser.print_help()
            sys.exit(0)
                
    except KeyboardInterrupt:
        # Use defaults if variables are not defined
        current_port_safe = locals().get('current_port', data_analysis_server_PORT)
        current_protocol_safe = locals().get('current_protocol', data_analysis_server_PROTOCOL)
        response, exit_code = create_response(
            True, 
            format_message('interrupt'),
            current_port=current_port_safe,
            current_protocol=current_protocol_safe
        )
    except Exception as e:
        # Use defaults if variables are not defined
        current_port_safe = locals().get('current_port', data_analysis_server_PORT)
        current_protocol_safe = locals().get('current_protocol', data_analysis_server_PROTOCOL)
        response, exit_code = create_response(
            False, 
            format_message('error', error=str(e)), 
            exit_code=1,
            current_port=current_port_safe,
            current_protocol=current_protocol_safe
        )
    finally:
        if 'response' in locals():
            json_output = False
            if 'args' in locals() and hasattr(args, 'json'):
                json_output = args.json
            print_response(response, exit_code, json_output)